"""MAP programs: the match-action sibling of Parser (parser.py).

Same shape end to end: states are functions decorated with ``@mp.state()``,
``build_ir()`` produces a nanuk.ir.v0 MatchActionProgram proto, ``compile()`` is
``nanuk.ir.map_lower.to_map_asm(build_ir())``. Tables are declared on the
program (``mp.table``) and referenced by lookups; headers are *bound* to
the PP's hdr ids (``mp.header(eth, hdr_id=0)``) so field access resolves to
hdr-relative byte addressing. The MAP is the byte machine: non-byte-aligned
fields are a CompileError.

Inbound-SMD field ids: 0-7 = PP SMD slots, MD_INGRESS = 8, MD_FLOOD = 9,
MD_HDRS = 10.
"""

import itertools
import re

from nanuk.ir import nanuk_ir_pb2 as ir
from nanuk.ir.pp_lower import LowerError
from nanuk.ir.map_lower import to_map_asm
from nanuk.ir.pp_validate import ValidationError
from nanuk.ir.map_validate import IR_VERSION

from .header import CompileError, Field, Header

_LABEL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_BANNER = "; generated by nanuk-lang\n\n"

MD_INGRESS = 8
MD_FLOOD = 9
MD_HDRS = 10

H_FRAME = 15

_N_TABLES = 4
_MAX_MD_FIELD = 15
_MIN_OFF, _MAX_OFF = -512, 511
_MAX_IMM16 = (1 << 16) - 1
_MIN_SIMM16, _MAX_SIMM16 = -(1 << 15), (1 << 15) - 1


class Table:
    """A declared exact-match table (entries are control-plane state)."""

    def __init__(self, table_id: int, name: str, key_width: int, action_width: int):
        self.table_id = table_id
        self.name = name
        self.key_width = key_width
        self.action_width = action_width

    def __repr__(self) -> str:
        return f"<table {self.name} (t{self.table_id})>"


class BoundField:
    """A header field resolved against a PP hdr id: byte-granular access."""

    def __init__(self, bound: "BoundHeader", field: Field):
        if field.bit_offset % 8 or field.width % 8:
            raise CompileError(
                f"{field.qualname} is not byte-aligned "
                f"(bit offset {field.bit_offset}, width {field.width}); the MAP "
                "is byte-granular — sub-byte fields are the parser's job"
            )
        if field.width // 8 > 8:
            raise CompileError(
                f"{field.qualname} is {field.width // 8} bytes; MAP loads/stores "
                "move at most 8"
            )
        self.hdr_id = bound.hdr_id
        self.byte_offset = field.bit_offset // 8
        self.nbytes = field.width // 8
        self.qualname = field.qualname

    def __repr__(self) -> str:
        return f"<bound {self.qualname}>"


class BoundHeader:
    """A Header bound to the PP's hdr id; attribute access yields BoundFields."""

    def __init__(self, header: Header, hdr_id: int):
        if not 0 <= hdr_id <= 15:
            raise CompileError(f"hdr_id {hdr_id!r} out of range 0..15")
        self._header = header
        self.hdr_id = hdr_id
        self.name = header.name

    def __getattr__(self, item: str) -> BoundField:
        field = getattr(self._header, item)
        if not isinstance(field, Field):
            raise CompileError(
                f"{self._header.name}.{item} is not a header field"
            )
        return BoundField(self, field)

    def __repr__(self) -> str:
        return f"<header {self.name} @ hdr {self.hdr_id}>"


class MatchActionValue:
    """Handle to a defined IR value (load/load_md/const/add/lookup result)."""

    def __init__(self, value_id: int, name: str):
        self.value_id = value_id
        self.name = name

    def __repr__(self) -> str:
        return f"<value {self.name}>"


class MatchActionState:
    """A registered MAP state; its name doubles as the assembly label."""

    def __init__(self, fn, start: bool):
        self.fn = fn
        self.name = fn.__name__
        self.start = start

    def __repr__(self) -> str:
        return f"<state {self.name}>"


class MatchActionProgram:
    def __init__(self):
        self._states: list[MatchActionState] = []
        self._tables: list[Table] = []

    def table(self, name: str, *, key_width: int, action_width: int) -> Table:
        """Declare an exact-match table; ids are assigned in declaration order."""
        if len(self._tables) >= _N_TABLES:
            raise CompileError(f"at most {_N_TABLES} tables (t0..t{_N_TABLES - 1})")
        if not 1 <= key_width <= 64:
            raise CompileError(f"key_width {key_width} out of range 1..64")
        if not 1 <= action_width <= 64:
            raise CompileError(f"action_width {action_width} out of range 1..64")
        t = Table(len(self._tables), name, key_width, action_width)
        self._tables.append(t)
        return t

    def header(self, header: Header, *, hdr_id: int) -> BoundHeader:
        """Bind a Header to the PP's hdr id for hdr-relative addressing."""
        if not isinstance(header, Header):
            raise CompileError(f"header expects a Header, got {header!r}")
        return BoundHeader(header, hdr_id)

    def state(self, fn=None, *, start: bool = False):
        """Decorator registering a MAP state, as Parser.state does."""

        def register(fn) -> MatchActionState:
            if not _LABEL_RE.match(fn.__name__):
                raise CompileError(f"state name {fn.__name__!r} is not a valid label")
            if any(st.name == fn.__name__ for st in self._states):
                raise CompileError(f"duplicate state name {fn.__name__!r}")
            st = MatchActionState(fn, start)
            self._states.append(st)
            return st

        if fn is not None:
            return register(fn)
        return register

    def build_ir(self) -> ir.MatchActionProgram:
        """Run every state body and return the nanuk.ir.v0 MatchActionProgram."""
        starts = [st for st in self._states if st.start]
        if len(starts) != 1:
            raise CompileError(
                f"expected exactly one start state, found {len(starts)}"
            )
        ordered = starts + [st for st in self._states if not st.start]
        states = set(self._states)
        value_ids = itertools.count(1)

        program = ir.MatchActionProgram(ir_version=IR_VERSION)
        for t in self._tables:
            program.tables.add(
                table_id=t.table_id,
                key_width=t.key_width,
                action_width=t.action_width,
                debug_name=t.name,
            )
        for st in ordered:
            sc = MatchActionStateCompiler(st.name, states, value_ids)
            st.fn(sc)
            if sc._terminator is None:
                raise CompileError(
                    f"state {st.name!r} does not end with a terminator "
                    "(send/drop/goto/dispatch)"
                )
            state_msg = program.states.add(name=st.name)
            state_msg.ops.extend(sc._ops)
            state_msg.terminator.CopyFrom(sc._terminator)
        return program

    def compile(self) -> str:
        """build_ir() + nanuk.ir MAP lowering; returns assembled program text."""
        program = self.build_ir()
        try:
            body = to_map_asm(program)
        except (LowerError, ValidationError) as e:
            raise CompileError(str(e)) from e
        return _BANNER + body


class MatchActionStateCompiler:
    """The ``s`` object handed to each @mp.state function; builds one MatchActionState."""

    def __init__(self, state_name: str, states: set, value_ids):
        self._state_name = state_name
        self._states = states
        self._value_ids = value_ids
        self._ops: list[ir.MatchActionOp] = []
        self._terminator: ir.Terminator | None = None

    # -- values ---------------------------------------------------------------

    def load(self, field, *, hdr=None, byte_offset=None, nbytes=None) -> MatchActionValue:
        """Load window bytes: either a bound header field, or raw
        (hdr=..., byte_offset=..., nbytes=...) addressing (headroom access)."""
        self._check_open()
        hdr_id, off, n, name = self._resolve_access("load", field, hdr, byte_offset, nbytes)
        v = MatchActionValue(next(self._value_ids), name)
        self._ops.append(
            ir.MatchActionOp(
                load=ir.MapLoad(
                    value_id=v.value_id, hdr_id=hdr_id, byte_offset=off,
                    nbytes=n, debug_name=name,
                )
            )
        )
        return v

    def load_md(self, field: int) -> MatchActionValue:
        """Load an inbound-SMD field (0-7 slots, MD_INGRESS/MD_FLOOD/MD_HDRS)."""
        self._check_open()
        if not isinstance(field, int) or not 0 <= field <= _MAX_MD_FIELD:
            raise CompileError(f"load_md field {field!r} out of range 0..{_MAX_MD_FIELD}")
        names = {MD_INGRESS: "ingress", MD_FLOOD: "flood", MD_HDRS: "hdr_present"}
        name = names.get(field, f"smd[{field}]")
        v = MatchActionValue(next(self._value_ids), name)
        self._ops.append(
            ir.MatchActionOp(load_md=ir.MapLoadMd(value_id=v.value_id, field=field, debug_name=name))
        )
        return v

    def const(self, imm: int, *, name: str | None = None) -> MatchActionValue:
        """Materialize a 16-bit constant (MOVI)."""
        self._check_open()
        if not isinstance(imm, int) or isinstance(imm, bool) or not 0 <= imm <= _MAX_IMM16:
            raise CompileError(f"const {imm!r} out of range 0..{_MAX_IMM16:#x}")
        v = MatchActionValue(next(self._value_ids), name or f"{imm:#x}")
        self._ops.append(
            ir.MatchActionOp(const=ir.MapConst(value_id=v.value_id, imm=imm, debug_name=v.name))
        )
        return v

    def add(self, value: MatchActionValue, imm: int) -> MatchActionValue:
        """value + signed 16-bit immediate (ADDI; 64-bit wraparound)."""
        self._check_open()
        self._require_value(value, "add")
        if not _MIN_SIMM16 <= imm <= _MAX_SIMM16:
            raise CompileError(f"add immediate {imm} out of signed 16-bit range")
        v = MatchActionValue(next(self._value_ids), f"{value.name} + {imm}")
        self._ops.append(
            ir.MatchActionOp(add=ir.MapAdd(value_id=v.value_id, src_value_id=value.value_id, imm=imm))
        )
        return v

    def lookup(self, table: Table, key: MatchActionValue, *, miss) -> MatchActionValue:
        """Exact-match lookup: hit continues with the action value; miss
        transfers to the `miss` state."""
        self._check_open()
        if not isinstance(table, Table):
            raise CompileError(f"lookup expects a declared table, got {table!r}")
        self._require_value(key, "lookup key")
        label = self._target_label(miss, "lookup miss")
        v = MatchActionValue(next(self._value_ids), f"{table.name}[{key.name}]")
        self._ops.append(
            ir.MatchActionOp(
                lookup=ir.Lookup(
                    value_id=v.value_id, table_id=table.table_id,
                    key_value_id=key.value_id, miss_state=label,
                )
            )
        )
        return v

    # -- statements -------------------------------------------------------------

    def store(self, value: MatchActionValue, field=None, *, hdr=None, byte_offset=None,
              nbytes=None) -> None:
        """Store the low bytes of a value: bound field or raw addressing."""
        self._check_open()
        self._require_value(value, "store")
        hdr_id, off, n, name = self._resolve_access(
            "store", field, hdr, byte_offset, nbytes
        )
        self._ops.append(
            ir.MatchActionOp(
                store=ir.MapStore(
                    value_id=value.value_id, hdr_id=hdr_id, byte_offset=off,
                    nbytes=n, debug_name=name,
                )
            )
        )

    def csum_update(self, header: BoundHeader, *, byte_offset: int = 0) -> None:
        """Recompute the IPv4 header checksum in place (CSUMUPD accelerator)."""
        self._check_open()
        if not isinstance(header, BoundHeader):
            raise CompileError(f"csum_update expects a bound header, got {header!r}")
        self._ops.append(
            ir.MatchActionOp(csum=ir.CsumUpdate(hdr_id=header.hdr_id, byte_offset=byte_offset))
        )

    # -- terminators --------------------------------------------------------------

    def send(self, bitmap: MatchActionValue, *, delta: int = 0) -> None:
        """Terminate: transmit to the port bitmap with a signed head delta."""
        self._check_open()
        self._require_value(bitmap, "send")
        if not _MIN_OFF <= delta <= _MAX_OFF:
            raise CompileError(f"send delta {delta} out of range")
        self._terminator = ir.Terminator(
            send=ir.MapSend(bitmap_value_id=bitmap.value_id, delta=delta)
        )

    def drop(self) -> None:
        """Terminate without output."""
        self._check_open()
        self._terminator = ir.Terminator(drop=ir.Drop())

    def goto(self, target) -> None:
        """Unconditional transfer to another state. Terminates the state."""
        self._check_open()
        label = self._target_label(target, "goto")
        self._terminator = ir.Terminator(goto=ir.Goto(target_state=label))

    def dispatch(self, value: MatchActionValue, arms: dict, *, default) -> None:
        """Compare-and-branch over 16-bit constants; default is a state or a
        callable terminator shorthand (s.drop). Terminates the state."""
        self._check_open()
        self._require_value(value, "dispatch")
        cases = []
        for const, target in arms.items():
            if not isinstance(const, int) or isinstance(const, bool) or const < 0:
                raise CompileError(f"dispatch constant {const!r} must be a non-negative int")
            if const > _MAX_IMM16:
                raise CompileError(
                    f"dispatch constant {const:#x} does not fit in 16 bits"
                )
            label = self._target_label(target, f"dispatch arm {const:#x}")
            cases.append(ir.Case(match=const, target_state=label))
        if default is self.drop:
            default_ir = ir.Terminator(drop=ir.Drop())
        else:
            label = self._target_label(default, "dispatch default")
            default_ir = ir.Terminator(goto=ir.Goto(target_state=label))
        self._terminator = ir.Terminator(
            dispatch=ir.Dispatch(value_id=value.value_id, cases=cases, default=default_ir)
        )

    # -- internals ---------------------------------------------------------------

    def _check_open(self) -> None:
        if self._terminator is not None:
            raise CompileError(
                f"state {self._state_name!r}: statement after the state was "
                "terminated by send/drop/goto/dispatch"
            )

    def _require_value(self, value, what: str) -> None:
        if not isinstance(value, MatchActionValue):
            raise CompileError(f"{what} expects a value handle, got {value!r}")

    def _target_label(self, target, what: str) -> str:
        if target not in self._states:
            raise CompileError(
                f"state {self._state_name!r}: {what} target {target!r} is not a "
                "state of this MAP program"
            )
        return target.name

    def _resolve_access(self, what, field, hdr, byte_offset, nbytes):
        if field is not None:
            if not isinstance(field, BoundField):
                raise CompileError(
                    f"{what} expects a bound header field (mp.header(...).x), "
                    f"got {field!r}"
                )
            if hdr is not None or byte_offset is not None or nbytes is not None:
                raise CompileError(
                    f"{what}: give either a bound field or raw addressing, not both"
                )
            return field.hdr_id, field.byte_offset, field.nbytes, field.qualname
        if hdr is None or byte_offset is None or nbytes is None:
            raise CompileError(
                f"{what}: raw addressing needs hdr=, byte_offset=, and nbytes="
            )
        hdr_id = hdr.hdr_id if isinstance(hdr, BoundHeader) else hdr
        if not isinstance(hdr_id, int) or not 0 <= hdr_id <= 15:
            raise CompileError(f"{what}: hdr {hdr!r} out of range 0..15")
        if not _MIN_OFF <= byte_offset <= _MAX_OFF:
            raise CompileError(f"{what}: byte offset {byte_offset} out of range")
        if not 1 <= nbytes <= 8:
            raise CompileError(f"{what}: nbytes {nbytes} out of range 1..8")
        name = f"win[{hdr_id}{byte_offset:+d}:{nbytes}]"
        return hdr_id, byte_offset, nbytes, name
