"""Parser programs: state registration, IR building, and compilation.

States are plain functions decorated with ``@p.state()``; the decorator
returns a State object usable as a dispatch/goto target (including forward
and self references — bodies only run at build time). ``build_ir()`` runs
every state body and returns a nanuk.ir.v0 Program proto (start state
first, the rest in definition order); ``compile()`` is the composition
``nanuk.ir.lower.to_asm(build_ir())`` and returns assembly text for
nanuk.testkit's assembler.
"""

import itertools
import re

from nanuk.ir import nanuk_ir_pb2 as ir
from nanuk.ir.lower import LowerError, to_asm
from nanuk.ir.validate import IR_VERSION, ValidationError

from .compile import StateCompiler
from .header import CompileError

_LABEL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_BANNER = "; generated by nanuk-lang\n\n"


class State:
    """A registered parse state; its name doubles as the assembly label."""

    def __init__(self, fn, start: bool):
        self.fn = fn
        self.name = fn.__name__
        self.start = start

    def __repr__(self) -> str:
        return f"<state {self.name}>"


class Parser:
    def __init__(self):
        self._states: list[State] = []

    def state(self, fn=None, *, start: bool = False):
        """Decorator registering a parse state: ``@p.state()`` / ``@p.state(start=True)``."""

        def register(fn) -> State:
            if not _LABEL_RE.match(fn.__name__):
                raise CompileError(f"state name {fn.__name__!r} is not a valid label")
            if any(st.name == fn.__name__ for st in self._states):
                raise CompileError(f"duplicate state name {fn.__name__!r}")
            st = State(fn, start)
            self._states.append(st)
            return st

        if fn is not None:  # bare @p.state
            return register(fn)
        return register

    def build_ir(self) -> ir.Program:
        """Run every state body and return the nanuk.ir.v0 Program."""
        starts = [st for st in self._states if st.start]
        if len(starts) != 1:
            raise CompileError(
                f"expected exactly one start state, found {len(starts)}"
            )
        ordered = starts + [st for st in self._states if not st.start]
        states = set(self._states)
        value_ids = itertools.count(1)  # ids unique per program, 0 reserved

        program = ir.Program(ir_version=IR_VERSION)
        for st in ordered:
            sc = StateCompiler(st.name, states, value_ids)
            st.fn(sc)
            if sc._terminator is None:
                raise CompileError(
                    f"state {st.name!r} does not end with a terminator "
                    "(accept/drop/goto/dispatch)"
                )
            state_msg = program.states.add(name=st.name)
            state_msg.ops.extend(sc._ops)
            state_msg.terminator.CopyFrom(sc._terminator)
        return program

    def compile(self) -> str:
        """build_ir() + nanuk.ir lowering; returns the assembled program text."""
        program = self.build_ir()
        try:
            body = to_asm(program)
        except (LowerError, ValidationError) as e:
            raise CompileError(str(e)) from e
        return _BANNER + body
