"""Parser programs: state registration and whole-program compilation.

States are plain functions decorated with ``@p.state()``; the decorator
returns a State object usable as a dispatch/goto target (including forward
and self references — bodies only run at compile() time). compile() emits
one label per state, start state first at word 0, the rest in definition
order, and returns assembly text for nanuk_spec's assembler.
"""

import re

from .compile import StateCompiler
from .header import CompileError

_LABEL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class State:
    """A registered parse state; its name doubles as the assembly label."""

    def __init__(self, fn, start: bool):
        self.fn = fn
        self.name = fn.__name__
        self.start = start

    def __repr__(self) -> str:
        return f"<state {self.name}>"


class Parser:
    def __init__(self):
        self._states: list[State] = []

    def state(self, fn=None, *, start: bool = False):
        """Decorator registering a parse state: ``@p.state()`` / ``@p.state(start=True)``."""

        def register(fn) -> State:
            if not _LABEL_RE.match(fn.__name__):
                raise CompileError(f"state name {fn.__name__!r} is not a valid label")
            if any(st.name == fn.__name__ for st in self._states):
                raise CompileError(f"duplicate state name {fn.__name__!r}")
            st = State(fn, start)
            self._states.append(st)
            return st

        if fn is not None:  # bare @p.state
            return register(fn)
        return register

    def compile(self) -> str:
        """Run every state body and return the assembled program text."""
        starts = [st for st in self._states if st.start]
        if len(starts) != 1:
            raise CompileError(
                f"expected exactly one start state, found {len(starts)}"
            )
        ordered = starts + [st for st in self._states if not st.start]
        states = set(self._states)

        lines: list[str] = ["; generated by nanuk-lang", ""]
        for st in ordered:
            lines.append(f"{st.name}:")
            sc = StateCompiler(st.name, states)
            st.fn(sc)
            if not sc._terminated:
                raise CompileError(
                    f"state {st.name!r} does not end with a terminator "
                    "(accept/drop/goto/dispatch)"
                )
            lines.extend(f"    {line}" for line in sc._lines)
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"
