"""Conformance guards for the committed SIIT vector suite
(benchmarks/siit/vectors/*.json, generated by benchmarks/siit/gen_vectors.py).

Three checks, each catching a different failure mode:
  - regen-byte-identical: the committed files are exactly what the generator
    produces today -- the drift tripwire (stale commits, hand edits, or a
    reference-translator change that forgot to regenerate).
  - every-vector-agrees-with-reference: replaying each committed vector
    through `translate()` reproduces its verdict/frame/why -- catches hand
    edits that happen to preserve JSON shape but not content.
  - vectors-cite-real-audit-anchors: every vector's `rfc` field names a real
    disposition ID from benchmarks/siit/audit.md, not a typo or a stale
    heading anchor.
"""

import importlib.util
import re
from pathlib import Path

from nanuk.testkit.siit_ref import VECTOR_GROUPS, load_vectors, translate

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SIIT_DIR = _REPO_ROOT / "benchmarks" / "siit"
_GEN_VECTORS_PATH = _SIIT_DIR / "gen_vectors.py"
_VECTORS_DIR = _SIIT_DIR / "vectors"
_AUDIT_PATH = _SIIT_DIR / "audit.md"

# Every disposition ID in the audit is backtick-quoted and starts with one of
# these three prefixes (7915-* for RFC 7915 clauses, 6052-*/7757-* for the
# delegated addressing clauses) -- see audit.md's "stable ID" convention.
_DISPOSITION_ID_RE = re.compile(r"`(7915-[\w.-]+|6052-[\w.-]+|7757-[\w.-]+)`")


def _load_gen_vectors():
    spec = importlib.util.spec_from_file_location("gen_vectors", _GEN_VECTORS_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_regen_is_byte_identical(tmp_path):
    gen = _load_gen_vectors()
    gen.write_groups(tmp_path)
    for group in VECTOR_GROUPS:
        committed = (_VECTORS_DIR / f"{group}.json").read_bytes()
        regenerated = (tmp_path / f"{group}.json").read_bytes()
        assert regenerated == committed, (
            f"{group}.json has drifted from `gen_vectors.py` -- regenerate and commit"
        )


def test_every_vector_agrees_with_reference():
    vectors = load_vectors()
    assert vectors, "sanity: there must be at least one committed vector"
    for v in vectors:
        r = translate(bytes.fromhex(v["in"]))
        assert r.verdict == v["verdict"], f"{v['name']}: verdict mismatch"
        if v["verdict"] == "sent":
            assert v["out"] is not None, f"{v['name']}: sent vector missing `out`"
            assert r.frame is not None and r.frame.hex() == v["out"], (
                f"{v['name']}: output frame mismatch"
            )
        else:
            assert v["out"] is None, f"{v['name']}: drop vector must have out=null"
            assert r.why == v["why"], f"{v['name']}: why mismatch"


def test_vectors_cite_real_audit_anchors():
    audit_text = _AUDIT_PATH.read_text()
    disposition_ids = set(_DISPOSITION_ID_RE.findall(audit_text))
    assert len(disposition_ids) > 50, "sanity: the audit should list dozens of disposition IDs"
    for v in load_vectors():
        assert v["rfc"] in disposition_ids, (
            f"{v['name']}: rfc={v['rfc']!r} is not a disposition ID in audit.md"
        )
