"""The eDSL -> IR seam: build_ir() emits valid nanuk.ir.v0 programs, and
compile() is exactly banner + lower(build_ir()) — including across a
protobuf serialize/deserialize round trip."""

from nanuk_ir import nanuk_ir_pb2 as ir
from nanuk_ir.lower import to_asm
from nanuk_ir.validate import validate

from nanuk_lang.programs.l2l3l4 import build, build_ir

BANNER = "; generated by nanuk-lang\n\n"


def test_build_ir_shape_and_validity():
    program = build_ir()
    validate(program)  # no exception
    assert program.ir_version == 1
    assert [st.name for st in program.states] == [
        "start", "vlan_tag", "ipv4_check", "ipv4_body", "udp_hdr",
    ]
    start = program.states[0]
    assert start.terminator.WhichOneof("kind") == "dispatch"
    first = start.ops[0]
    assert first.WhichOneof("op") == "mark"
    assert first.mark.emit_sethdr and first.mark.hdr_id == 0
    # ipv4_body's mark is a re-anchor only: no SETHDR after lowering.
    body_mark = program.states[3].ops[0]
    assert body_mark.WhichOneof("op") == "mark" and not body_mark.mark.emit_sethdr


def test_compile_is_banner_plus_lowered_ir():
    assert BANNER + to_asm(build_ir()) == build()


def test_ir_round_trip_lowers_byte_identically():
    program = build_ir()
    direct = to_asm(program)

    wire = program.SerializeToString()
    reparsed = ir.Program()
    reparsed.ParseFromString(wire)

    assert to_asm(reparsed) == direct


def test_value_ids_are_unique_per_program():
    program = build_ir()
    seen = set()
    for state in program.states:
        for op in state.ops:
            match op.WhichOneof("op"):
                case "extract":
                    vid = op.extract.value_id
                case "shift":
                    vid = op.shift.value_id
                case _:
                    continue
            assert vid >= 1 and vid not in seen
            seen.add(vid)
