; generated by nanuk-lang

start:
    sethdr  0                  ; eth
    ext     r0, 0, 48          ; eth.dst
    stmd    1, r0, 3           ; eth.dst
    ext     r1, 96, 16         ; eth.ethertype
    advi    14
    movi    r3, 0x8100
    beq     r1, r3, vlan_tag   ; eth.ethertype
    movi    r3, 0x0800
    beq     r1, r3, ipv4_check ; eth.ethertype
    halt    accept

vlan_tag:
    sethdr  1                  ; vlan
    ext     r0, 0, 16          ; vlan.tci
    stmd    4, r0, 1           ; vlan.tci
    ext     r1, 16, 16         ; vlan.ethertype
    advi    4
    movi    r3, 0x8100
    beq     r1, r3, vlan_tag   ; vlan.ethertype
    movi    r3, 0x0800
    beq     r1, r3, ipv4_check ; vlan.ethertype
    halt    accept

ipv4_check:
    sethdr  2                  ; ipv4
    ext     r0, 0, 4           ; ipv4.version
    movi    r3, 0x0004
    beq     r0, r3, ipv4_body  ; ipv4.version
    halt    drop

ipv4_body:
    ext     r0, 4, 4           ; ipv4.ihl
    ext     r1, 72, 8          ; ipv4.proto
    shl     r2, r0, 2          ; ipv4.ihl << 2
    advr    r2                 ; ipv4.ihl << 2
    movi    r3, 0x0011
    beq     r1, r3, udp_hdr    ; ipv4.proto
    halt    accept

udp_hdr:
    sethdr  3                  ; udp
    ext     r0, 16, 16         ; udp.dport
    stmd    5, r0, 1           ; udp.dport
    advi    8
    halt    accept
